/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package duan1_qlbantrasua.Views;

import duan1_qlbantrasua.DomainModels.CTGioHang;
import duan1_qlbantrasua.DomainModels.HoaDon;
import duan1_qlbantrasua.DomainModels.HoaDonChiTiet;
import duan1_qlbantrasua.DomainModels.MucDa;
import duan1_qlbantrasua.DomainModels.MucDuong;
import duan1_qlbantrasua.DomainModels.NhanVien;
import duan1_qlbantrasua.DomainModels.SanPham;
import duan1_qlbantrasua.DomainModels.Topping;
import duan1_qlbantrasua.Services.CTGHServiece;
import duan1_qlbantrasua.Services.HDCTService;
import duan1_qlbantrasua.Services.HoaDonService;
import duan1_qlbantrasua.Services.SanPhamService;
import duan1_qlbantrasua.Services.impl.CTGHServiceImpl;
import duan1_qlbantrasua.Services.impl.HDCTServiceImpl;
import duan1_qlbantrasua.Services.impl.HoaDonServiceImpl;
import duan1_qlbantrasua.Services.impl.SanPhamServiceImpl;
import duan1_qlbantrasua.ViewModels.HDBHViewModel;
import duan1_qlbantrasua.ViewModels.SanPhamFromBanHang;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TrungVD
 */
public class MainBanHangView extends javax.swing.JPanel {

    private HoaDonService qLHoaDon;
    private SanPhamService qLSanPham;
    private CTGHServiece qLCTGH;
    private HDCTService qLHDCT;
    private DefaultTableModel dtm;
    private ArrayList<CTGioHang> listCTGH;
    private NhanVien nhanVienLogin;

    public MainBanHangView() {
        initComponents();
        init();
        loadTableHDChuaThanhToan(qLHoaDon.getListHDChuaThanhToan());
        loadTableHDDaThanhToan(qLHoaDon.getListHDDaThanhToan());
        loadTableHDHuyThanhToan(qLHoaDon.getListHDHuyThanhToan());
        loadTableSanpham(qLSanPham.getListSPFormBH());
        if(txtTienKhachDua.getText().isEmpty() || txtTienKhachDua.getText().equalsIgnoreCase("0")){
            btnThanhToan.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblHoaDonChoThanhToan = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDaThanhToan = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHuyThanhToan = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        btnLamMoiGioHang = new javax.swing.JButton();
        btnXoaMon = new javax.swing.JButton();
        btnTaoHoaDon = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        txtNgayTao = new javax.swing.JTextField();
        txtMaHoaDon = new javax.swing.JTextField();
        txtHoTenKhachHang = new javax.swing.JTextField();
        txtMaKhachHang = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        txtTongTienHang = new javax.swing.JTextField();
        txtGiamGia = new javax.swing.JTextField();
        txtTienKhachDua = new javax.swing.JTextField();
        txtKhachCanTra = new javax.swing.JTextField();
        txtTienTraLai = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        txaGhiChu = new javax.swing.JTextArea();
        btnHuy = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Quản Lý Bán Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Thông Tin Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        tblHoaDonChoThanhToan.setBackground(new java.awt.Color(0, 51, 153));
        tblHoaDonChoThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblHoaDonChoThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        tblHoaDonChoThanhToan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Tên Nhân Viên", "Ngày Tạo", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDonChoThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonChoThanhToanMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblHoaDonChoThanhToan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Chờ Thanh Toán", jPanel3);

        tblDaThanhToan.setBackground(new java.awt.Color(0, 204, 102));
        tblDaThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        tblDaThanhToan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Tên Nhân Viên", "Ngày Tạo", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDaThanhToan);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Đã Thanh Toán", jPanel4);

        tblHuyThanhToan.setBackground(new java.awt.Color(204, 51, 0));
        tblHuyThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        tblHuyThanhToan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Tên Nhân Viên", "Ngày Tạo", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblHuyThanhToan);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Hóa Đơn Hủy", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jPanel6.setBackground(new java.awt.Color(102, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Thông Tin Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        tblSanPham.setBackground(new java.awt.Color(0, 0, 153));
        tblSanPham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblSanPham.setForeground(new java.awt.Color(255, 255, 255));
        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Sản Phẩm", "Giá", "Danh Mục", "Hình Ảnh", "Mô Tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblSanPham);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane5)
                .addGap(0, 0, 0))
        );

        jPanel7.setBackground(new java.awt.Color(102, 204, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Giỏ Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        tblGioHang.setBackground(new java.awt.Color(0, 51, 153));
        tblGioHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblGioHang.setForeground(new java.awt.Color(255, 255, 255));
        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên Món", "Số Lượng", "Mức Đường", "Mức Đá", "Topping", "Tổng Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblGioHang);

        btnLamMoiGioHang.setBackground(new java.awt.Color(102, 204, 255));
        btnLamMoiGioHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan1_qlbantrasua/Views/icon/loading.png"))); // NOI18N
        btnLamMoiGioHang.setBorder(null);
        btnLamMoiGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiGioHangActionPerformed(evt);
            }
        });

        btnXoaMon.setBackground(new java.awt.Color(102, 204, 255));
        btnXoaMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan1_qlbantrasua/Views/icon/deleteSP.png"))); // NOI18N
        btnXoaMon.setBorder(null);
        btnXoaMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaMonActionPerformed(evt);
            }
        });

        btnTaoHoaDon.setBackground(new java.awt.Color(0, 204, 204));
        btnTaoHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTaoHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnTaoHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan1_qlbantrasua/Views/icon/add.png"))); // NOI18N
        btnTaoHoaDon.setText("Tạo Hóa Đơn");
        btnTaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnTaoHoaDon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoaMon)
                .addGap(18, 18, 18)
                .addComponent(btnLamMoiGioHang)
                .addGap(22, 22, 22))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoaMon)
                    .addComponent(btnTaoHoaDon)
                    .addComponent(btnLamMoiGioHang)))
        );

        jPanel8.setBackground(new java.awt.Color(102, 204, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Thông Tin Đơn Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setText("Tên Nhân Viên");

        jLabel2.setText("Mã Hóa Đơn");

        jLabel3.setText("Ngày Tạo");

        jLabel4.setText("Mã Khách Hàng");

        jLabel5.setText("Họ Tên");

        jLabel6.setText("Điểm Khách Hàng");

        jLabel7.setText("Tổng Tiền Hàng");

        jLabel8.setText("Giảm Giá");

        jLabel9.setText("Khách Cần Trả");

        jLabel10.setText("Tiền Khách Đưa");
        jLabel10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel10KeyPressed(evt);
            }
        });

        jLabel11.setText("Tiền Trả Lại");

        jLabel12.setText("Kiểu Thanh Toán");

        jLabel13.setText("Ghi Chú");

        txtGiamGia.setText("0");
        txtGiamGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGiamGiaKeyPressed(evt);
            }
        });

        txtTienKhachDua.setText("0");
        txtTienKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyPressed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền Mặt", "Chuyển Khoản" }));

        txaGhiChu.setColumns(20);
        txaGhiChu.setRows(5);
        jScrollPane6.setViewportView(txaGhiChu);

        btnHuy.setBackground(new java.awt.Color(255, 51, 51));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Hủy");
        btnHuy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnThanhToan.setBackground(new java.awt.Color(0, 204, 0));
        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txtHoTenKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txtNgayTao, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txtTenNhanVien)
                            .addComponent(txtMaHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jLabel13)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, Short.MAX_VALUE)))
                .addGap(47, 47, 47)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, 130, Short.MAX_VALUE)
                    .addComponent(txtTienTraLai)
                    .addComponent(txtTienKhachDua)
                    .addComponent(txtKhachCanTra)
                    .addComponent(txtGiamGia)
                    .addComponent(txtTongTienHang)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTienHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKhachCanTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel10)
                        .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(txtHoTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienTraLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHoaDonActionPerformed
        NhanVien nhanVien = new NhanVien(nhanVienLogin.getId(), nhanVienLogin.getMa(), nhanVienLogin.getHoVaTen());
        System.out.println(nhanVien.getId());
        int sTT = qLHoaDon.getListHDChoDB().size() + 1;
        String maHD = "HD" + String.valueOf(sTT);
        HoaDon hoaDon = new HoaDon(maHD, new Date(), nhanVien);
        qLHoaDon.themHoaDon(hoaDon);
        loadTableHDChuaThanhToan(qLHoaDon.getListHDChuaThanhToan());
    }//GEN-LAST:event_btnTaoHoaDonActionPerformed

    private void tblHoaDonChoThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonChoThanhToanMouseClicked
        int row = tblHoaDonChoThanhToan.getSelectedRow();
        HoaDon hoaDon = qLHoaDon.getListHDChoDB().get(row);
        txtMaHoaDon.setText(hoaDon.getMa());
        txtTenNhanVien.setText(hoaDon.getNhanVien().getHoVaTen());
        txtNgayTao.setText(hoaDon.getNgayTao().toString());
        this.listCTGH = qLCTGH.getListCTGioHang(txtMaHoaDon.getText());
        loadTableGioHang(listCTGH);

    }//GEN-LAST:event_tblHoaDonChoThanhToanMouseClicked

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        if (txtMaHoaDon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa chọn hóa đơn cần thêm sản phẩm!");
            return;
        }
        int indexHoaDon = tblHoaDonChoThanhToan.getSelectedRow();
        int indexSanPham = tblSanPham.getSelectedRow();
        String tenSanPham = tblSanPham.getValueAt(indexSanPham, 0).toString();
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có thêm " + tenSanPham + " vào giỏ hàng không?");
        if (confirm == JOptionPane.YES_OPTION) {
            MainFormView mainFormView = null;
            OptionSanPhamView option = new OptionSanPhamView(mainFormView, true);
            option.setEditDaTa(qLSanPham.getListSanPhamDB().get(indexSanPham));
            option.setEditThongTin(qLHoaDon.getListHDChoDB().get(indexHoaDon));
            option.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Chưa thêm sản phẩm");
            return;
        }
        this.listCTGH = qLCTGH.getListCTGioHang(txtMaHoaDon.getText());
        loadTableGioHang(listCTGH);
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void txtGiamGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiamGiaKeyPressed
//        double tongTienHang = Double.parseDouble(txtTongTienHang.getText());
//        double tienGiamGia = Double.parseDouble(txtGiamGia.getText());
//        double tienPhaiTra = tongTienHang - tienGiamGia;
//        txtKhachCanTra.setText(String.valueOf(tienPhaiTra));
    }//GEN-LAST:event_txtGiamGiaKeyPressed

    private void txtTienKhachDuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyPressed
        double tienKhachDua = Double.parseDouble(txtTienKhachDua.getText());
        double tienPhaiTra = Double.parseDouble(txtKhachCanTra.getText());
        double tienTraLai = tienKhachDua - tienPhaiTra;
        if (tienKhachDua >= tienPhaiTra) {
            btnThanhToan.setEnabled(true);
        } else {
            btnThanhToan.setEnabled(false);
        }
        txtTienTraLai.setText(String.valueOf(tienTraLai));
    }//GEN-LAST:event_txtTienKhachDuaKeyPressed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        if (txtMaHoaDon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Hóa Đơn cần thanh toán!");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn thanh toán hóa đơn " + txtMaHoaDon.getText());
        if (confirm == JOptionPane.YES_OPTION) {
            int rowHoaDon = tblHoaDonChoThanhToan.getSelectedRow();
            ArrayList<CTGioHang> list = listCTGH;
            ArrayList<HoaDonChiTiet> listHDCT = new ArrayList();
            System.out.println(listCTGH.size());
            for (CTGioHang sanPhamGioHang : list) {
                HoaDon hoaDon = qLHoaDon.getListHDChoDB().get(rowHoaDon);
                SanPham sanPham = new SanPham(sanPhamGioHang.getIdSanPham(), sanPhamGioHang.getTenSanPham());
                MucDa mucDa = new MucDa(sanPhamGioHang.getIdDa(), sanPhamGioHang.getTenDa());
                MucDuong mucDuong = new MucDuong(sanPhamGioHang.getIdDuong(), sanPhamGioHang.getTenDuong());
                Topping topping = new Topping(sanPhamGioHang.getIdTopping(), sanPhamGioHang.getTenTopping());
                HoaDonChiTiet hoaDonChiTiet = new HoaDonChiTiet(hoaDon, sanPham, sanPhamGioHang.getDongGia(), sanPhamGioHang.getSoLuongSP(), mucDuong, mucDa, topping, mucDuong.getGia(), mucDa.getGia(), topping.getGia());
                listHDCT.add(hoaDonChiTiet);
            }
            for (HoaDonChiTiet hoaDonChiTiet : listHDCT) {
                qLHDCT.themHDCT(hoaDonChiTiet);
            }
            HoaDon hoaDon = new HoaDon(Double.parseDouble(txtTongTienHang.getText()), Double.parseDouble(txtGiamGia.getText()), Double.parseDouble(txtKhachCanTra.getText()), new Date(), txaGhiChu.getText(), 1);
            String maHoaDon = txtMaHoaDon.getText();
            JOptionPane.showMessageDialog(this, qLHoaDon.updateHoaDon(hoaDon, maHoaDon));
            qLCTGH.xoaCTGHKhiThanhToan(maHoaDon);
            loadTableHDChuaThanhToan(qLHoaDon.getListHDChuaThanhToan());
            loadTableHDDaThanhToan(qLHoaDon.getListHDDaThanhToan());
            JOptionPane.showMessageDialog(this, "Thanh toán thành công hhoas đơn " + txtMaHoaDon.getText());
            clearTableGioHang();
        }

    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        if (txtMaHoaDon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Hóa Đơn cần hủy!");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn hủy hóa đơn này không?");
        if (confirm == JOptionPane.YES_OPTION) {
            String lyDoHuy = JOptionPane.showInputDialog("Mời bạn nhập lý do hủy");
            String maHoaDon = txtMaHoaDon.getText();
            JOptionPane.showMessageDialog(this, qLHoaDon.huyHoaDon(lyDoHuy, maHoaDon));
            loadTableHDChuaThanhToan(qLHoaDon.getListHDChuaThanhToan());
            loadTableHDHuyThanhToan(qLHoaDon.getListHDHuyThanhToan());
        }
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnLamMoiGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiGioHangActionPerformed
        if (txtMaHoaDon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa có thông tin hóa đơn cần làm mới!");
            return;
        }
        String maHoaDon = txtMaHoaDon.getText();
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa hết sản phậm đang chọn không?");
        if(confirm == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, qLCTGH.xoaToanBoGioHang(maHoaDon));
            clearTableGioHang();
        }
        
    }//GEN-LAST:event_btnLamMoiGioHangActionPerformed

    private void btnXoaMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaMonActionPerformed
        if (txtMaHoaDon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Hóa Đơn cần xóa món!");
            return;
        }
        String maHoaDon = txtMaHoaDon.getText();
        ArrayList<CTGioHang> listGioHang = qLCTGH.getListCTGioHang(maHoaDon);
        System.out.println(listGioHang.size());
        int index = tblGioHang.getSelectedRow();
        System.out.println(index);
        CTGioHang sanPhamChiTiet = listGioHang.get(index);
        String idCTGH = sanPhamChiTiet.getId();
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa sản phẩm khỏi giỏ hàng không?");
        if (confirm == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, qLCTGH.xoaCTGH(idCTGH));
            loadTableGioHang(qLCTGH.getListCTGioHang(maHoaDon));
        }

    }//GEN-LAST:event_btnXoaMonActionPerformed

    private void jLabel10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel10KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLamMoiGioHang;
    private javax.swing.JButton btnTaoHoaDon;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnXoaMon;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTable tblDaThanhToan;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTable tblHoaDonChoThanhToan;
    private javax.swing.JTable tblHuyThanhToan;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextArea txaGhiChu;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtHoTenKhachHang;
    private javax.swing.JTextField txtKhachCanTra;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JTextField txtTienKhachDua;
    private javax.swing.JTextField txtTienTraLai;
    private javax.swing.JTextField txtTongTienHang;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.qLHoaDon = new HoaDonServiceImpl();
        this.qLSanPham = new SanPhamServiceImpl();
        this.qLCTGH = new CTGHServiceImpl();
        this.qLSanPham = new SanPhamServiceImpl();
        this.qLHDCT = new HDCTServiceImpl();
    }

    private void loadTableHDChuaThanhToan(ArrayList<HDBHViewModel> listHDChuaThanhToan) {
        dtm = (DefaultTableModel) tblHoaDonChoThanhToan.getModel();
        dtm.setRowCount(0);

        for (HDBHViewModel hoaDon : listHDChuaThanhToan) {
            dtm.addRow(new Object[]{
                hoaDon.getMaHoaDon(),
                hoaDon.getTenNhanVien(),
                hoaDon.getNgayTao(),
                hoaDon.getTrangThai() == 0 ? "Chờ thanh toán" : hoaDon.getTrangThai() == 1 ? "Đã thanh toán" : "Hủy thanh toán"
            });
        }
    }

    private void loadTableHDDaThanhToan(ArrayList<HDBHViewModel> listHDDaThanhToan) {
        dtm = (DefaultTableModel) tblDaThanhToan.getModel();
        dtm.setRowCount(0);
        for (HDBHViewModel hoaDon : listHDDaThanhToan) {
            dtm.addRow(new Object[]{
                hoaDon.getMaHoaDon(),
                hoaDon.getTenNhanVien(),
                hoaDon.getNgayTao(),
                hoaDon.getTrangThai() == 0 ? "Chờ thanh toán" : hoaDon.getTrangThai() == 1 ? "Đã thanh toán" : "Hủy thanh toán"
            });
        }
    }

    private void loadTableHDHuyThanhToan(ArrayList<HDBHViewModel> listHDHuyThanhToan) {
        dtm = (DefaultTableModel) tblHuyThanhToan.getModel();
        dtm.setRowCount(0);
        for (HDBHViewModel hoaDon : listHDHuyThanhToan) {
            dtm.addRow(new Object[]{
                hoaDon.getMaHoaDon(),
                hoaDon.getTenNhanVien(),
                hoaDon.getNgayTao(),
                hoaDon.getTrangThai() == 0 ? "Chờ thanh toán" : hoaDon.getTrangThai() == 1 ? "Đã thanh toán" : "Hủy thanh toán"
            });
        }
    }

    private void loadTableSanpham(ArrayList<SanPhamFromBanHang> listSPFormBH) {
        dtm = (DefaultTableModel) tblSanPham.getModel();
        dtm.setRowCount(0);
        for (SanPhamFromBanHang sanPham : listSPFormBH) {
            dtm.addRow(new Object[]{
                sanPham.getTenSanPham(),
                sanPham.getGiaSanPham(),
                sanPham.getTenDanhMuc(),
                sanPham.getDuongDanAnh(),
                sanPham.getMoTa()
            });
        }
    }

    private void loadTableGioHang(ArrayList<CTGioHang> listCTGioHang) {
        this.listCTGH = qLCTGH.getListCTGioHang(txtMaHoaDon.getText());
        dtm = (DefaultTableModel) tblGioHang.getModel();
        dtm.setRowCount(0);
        int sTT = 1;
        double tongTienHang = 0;
        for (CTGioHang sanPham : listCTGioHang) {
            dtm.addRow(new Object[]{
                sTT++,
                sanPham.getTenSanPham(),
                sanPham.getSoLuongSP(),
                sanPham.getTenDuong(),
                sanPham.getTenDa(),
                sanPham.getTenTopping(),
                sanPham.getTongTien()
            });
            tongTienHang = tongTienHang + sanPham.getTongTien();
        }
        txtTongTienHang.setText(String.valueOf(tongTienHang));
        double tienGiamGia = Double.parseDouble(txtGiamGia.getText());
        double tienPhaiTra = tongTienHang - tienGiamGia;
        txtKhachCanTra.setText(String.valueOf(tienPhaiTra));
    }

    void editData(NhanVien nhanVienDangNhapThanhCong) {
        System.out.println("abc");
        NhanVien nhanVien = new NhanVien();
        nhanVien.setId(nhanVienDangNhapThanhCong.getId());
        nhanVien.setMa(nhanVienDangNhapThanhCong.getMa());
        nhanVien.setHoVaTen(nhanVienDangNhapThanhCong.getHoVaTen());
        this.nhanVienLogin = nhanVien;
    }

    private void clearForm() {
        txtTenNhanVien.setText("");
        txtMaHoaDon.setText("");
        txtNgayTao.setText("");
        txtMaKhachHang.setText("");
        txaGhiChu.setText("");
        txtTongTienHang.setText("0");
        txtGiamGia.setText("0");
        txtKhachCanTra.setText("0");
        txtTienTraLai.setText("0");
    }

    private void clearTableGioHang() {
        tblGioHang.setModel(new DefaultTableModel(null, new String[]{
            "STT", "Tên Món", "Số Lượng", "Mức Đường", "Mức Đá", "Topping", "Tổng Tiền"
        }));
    }

}
